---

- hosts: 10.0.0.6
  become: yes
  tasks:

     - name: Check if apache is installed?
       stat:
         path: /etc/httpd/conf/httpd.conf
       register: check_pkg

     - name: Install Apache
       yum:
         name: httpd
         state: latest
       when: check_pkg.stat.exists == False


     - name: Configure Index page
       copy:
         dest: "/var/www/html/index.html"
         content: |
           Welcome to GIT WorkShop !!
       register: index

     - name: Restart httpd service
       service:
         name: httpd
         state: restarted
         enabled: yes
       when: check_pkg.stat.exists == False
